### ISSUE TITLE
Design chat page.

### ISSUE THREAD

**Issue by Rexhgx** [Rexhgx/CSE312#5]

**Comment by wangsnuxiao** [comment]
Hi

**Comment by Rexhgx** [comment]
https://codepen.io/adamleithp/pen/hcgkI
https://codepen.io/search/pens?q=profile&cursor=ZD0xJm89MCZwPTE5

**Comment by Rexhgx** [comment]
https://codepen.io/adamleithp/pen/hcgkI
https://codepen.io/search/pens?q=profile&cursor=ZD0xJm89MCZwPTE5
